export default {
	 jsonReduce(obj) {
    // Create a new object to avoid mutating the original data
    const output = Array.isArray(obj) ? [] : {};

    // Iterate through each key in the object or index in the array
    Object.keys(obj).forEach(key => {
        const value = obj[key];

        // If the value is an object or array, recurse into it
        if (value && typeof value === 'object') {
            const reduced = jsonReduce(value);
            // Only add the reduced value if it's not an empty object or array
            if (Array.isArray(reduced) && reduced.length > 0) {
                output[key] = reduced;
            } else if (!Array.isArray(reduced) && Object.keys(reduced).length > 0) {
                output[key] = reduced;
            }
        } else if (value !== null) { // Add the value if it's not null
            output[key] = value;
        }
    });

    return output;
	},
  categorizeData() {
    return CaseData.data.map(entry => {
      return {
        Base: {
          entry_id: entry.entry_id,
          website_domain: entry.website_domain,
          website_logo: entry.website_logo,
          website_link: entry.website_link,
          store_name: entry.store_name,
          case_category: entry.case_category,
          associated_listing_name: entry.associated_listing_name,
          associated_listing_profile_link: entry.associated_listing_profile_link,
          incident_date: entry.incident_date,
          updated_at: entry.updated_at,
          //},
          //Meta: {
          top_level_domain: entry.top_level_domain,
          subdomain: entry.subdomain,
          root_domain: entry.root_domain
        },
        Evidences: {
          website_classification: entry.website_classification,
          website_sub_classification: entry.website_sub_classification,
          violation_classification: entry.violation_classification,
          violating_content_classification: entry.violating_content_classification,
          violating_content_sub_classification: entry.violating_content_sub_classification,
          violation_severity: entry.violation_severity,
          global_violating_entities: entry.global_violating_entities,
          local_violating_entities: entry.local_violating_entities,
          site_accessible_local: entry.site_accessible_local,
          site_accessible_proxy_vpn: entry.site_accessible_proxy_vpn,
          screenshots_recordings: entry.screenshots_recordings,
          proxy_alias_site: entry.proxy_alias_site,
          primary_domain: entry.primary_domain,
          legal_report: entry.legal_report,
          historical_whois_report: entry.historical_whois_report,
          historical_website_structure: entry.historical_website_structure,
          reverse_email_search_evidences: entry.reverse_email_search_evidences,
          reverse_phone_search_evidences: entry.reverse_phone_search_evidences,
          reverse_search_keyword: entry.reverse_search_keyword,
          reverse_search_keyword_evidences: entry.reverse_search_keyword_evidences,
          primary_ad_network: entry.primary_ad_network,
          primary_ad_network_client_id: entry.primary_ad_network_client_id,
          primary_ad_network_screenshot: entry.primary_ad_network_screenshot,
          primary_payment_method: entry.primary_payment_method,
          primary_payment_method_id: entry.primary_payment_method_id,
          primary_payment_method_id_definition: entry.primary_payment_method_id_definition,
          primary_payment_method_screenshot: entry.primary_payment_method_screenshot,
          reverse_payment_method_id_evidences: entry.reverse_payment_method_id_evidences,
          crypto_wallets: entry.crypto_wallets,
          crypto_wallets_hash: entry.crypto_wallets_hash,
          crypto_wallets_page_screenshot: entry.crypto_wallets_page_screenshot,
          reverse_crypto_wallets_hash_evidences: entry.reverse_crypto_wallets_hash_evidences,
          banking_details: entry.banking_details,
          reverse_banking_details_evidences: entry.reverse_banking_details_evidences,
          transaction_evidences: entry.transaction_evidences,
          identified_user_name: entry.identified_user_name,
          identified_user_email: entry.identified_user_email,
          identified_user_phone: entry.identified_user_phone,
          identified_user_other_contact: entry.identified_user_other_contact,
          identified_user_investigation_data: entry.identified_user_investigation_data
        },
        Action: {
          reported_date: entry.reported_date,
          approved_date: entry.approved_date,
          resolved_date: entry.resolved_date,
          enforcement_outcome: entry.enforcement_outcome,
          enforcement_outcome_description: entry.enforcement_outcome_description,
          case_notes: entry.case_notes
        },
        Hosting: {
          IPv4: {
            server_ip_v4: entry.server_ip_v4,
            server_location_v4: entry.server_location_v4,
            reverse_dns_v4: entry.reverse_dns_v4,
            asn_number_v4: entry.asn_number_v4,
            asn_name_v4: entry.asn_name_v4,
            asn_registration_date_v4: entry.asn_registration_date_v4,
            asn_org_id_v4: entry.asn_org_id_v4,
            asn_address_v4: entry.asn_address_v4,
            asn_city_v4: entry.asn_city_v4,
            asn_state_prov_v4: entry.asn_state_prov_v4,
            asn_postal_code_v4: entry.asn_postal_code_v4,
            asn_country_v4: entry.asn_country_v4,
            reverse_ip_total_domains_v4: entry.reverse_ip_total_domains_v4,
            asn_org_tech_handle_v4: entry.asn_org_tech_handle_v4,
            asn_org_tech_name_v4: entry.asn_org_tech_name_v4,
            asn_org_tech_phone_v4: entry.asn_org_tech_phone_v4,
            asn_org_tech_email_v4: entry.asn_org_tech_email_v4,
            asn_org_tech_ref_v4: entry.asn_org_tech_ref_v4,
            asn_org_abuse_handle_v4: entry.asn_org_abuse_handle_v4,
            asn_org_abuse_name_v4: entry.asn_org_abuse_name_v4,
            asn_org_abuse_phone_v4: entry.asn_org_abuse_phone_v4,
            asn_org_abuse_email_v4: entry.asn_org_abuse_email_v4,
            asn_org_abuse_ref_v4: entry.asn_org_abuse_ref_v4,
            public_reporting_email_v4: entry.public_reporting_email_v4,
            public_reporting_phone_v4: entry.public_reporting_phone_v4,
            public_reporting_form_v4: entry.public_reporting_form_v4,
            hidden_isp_v4: entry.hidden_isp_v4,
            hidden_isp_contact_v4: entry.hidden_isp_contact_v4
          },
          IPv6: {
            server_ip_v6: entry.server_ip_v6,
            server_location_v6: entry.server_location_v6,
            reverse_dns_v6: entry.reverse_dns_v6,
            asn_number_v6: entry.asn_number_v6,
            asn_name_v6: entry.asn_name_v6,
            asn_registration_date_v6: entry.asn_registration_date_v6,
            asn_org_id_v6: entry.asn_org_id_v6,
            asn_address_v6: entry.asn_address_v6,
            asn_city_v6: entry.asn_city_v6,
            asn_state_prov_v6: entry.asn_state_prov_v6,
            asn_postal_code_v6: entry.asn_postal_code_v6,
            asn_country_v6: entry.asn_country_v6,
            reverse_ip_total_domains_v6: entry.reverse_ip_total_domains_v6,
            asn_org_tech_handle_v6: entry.asn_org_tech_handle_v6,
            asn_org_tech_name_v6: entry.asn_org_tech_name_v6,
            asn_org_tech_phone_v6: entry.asn_org_tech_phone_v6,
            asn_org_tech_email_v6: entry.asn_org_tech_email_v6,
            asn_org_tech_ref_v6: entry.asn_org_tech_ref_v6,
            asn_org_abuse_handle_v6: entry.asn_org_abuse_handle_v6,
            asn_org_abuse_name_v6: entry.asn_org_abuse_name_v6,
            asn_org_abuse_phone_v6: entry.asn_org_abuse_phone_v6,
            asn_org_abuse_email_v6: entry.asn_org_abuse_email_v6,
            asn_org_abuse_ref_v6: entry.asn_org_abuse_ref_v6,
            public_reporting_email_v6: entry.public_reporting_email_v6,
            public_reporting_phone_v6: entry.public_reporting_phone_v6,
            public_reporting_form_v6: entry.public_reporting_form_v6,
            hidden_isp_v6: entry.hidden_isp_v6,
            hidden_isp_contact_v6: entry.hidden_isp_contact_v6
          }
        },
        Registrar: {
          registry_domain_id: entry.registry_domain_id,
          registrar_whois_server: entry.registrar_whois_server,
          registrar_url: entry.registrar_url,
          domain_updated_date: entry.domain_updated_date,
          domain_creation_date: entry.domain_creation_date,
          registrar_name: entry.registrar_name,
          registrar_iana_id: entry.registrar_iana_id,
          registrar_abuse_contact_email: entry.registrar_abuse_contact_email,
          registrar_abuse_contact_phone: entry.registrar_abuse_contact_phone,
          registry_registrant_id: entry.registry_registrant_id,
          registrant_name: entry.registrant_name,
          registrant_organization: entry.registrant_organization,
          registrant_street: entry.registrant_street,
          registrant_city: entry.registrant_city,
          registrant_state_province: entry.registrant_state_province,
          registrant_postal_code: entry.registrant_postal_code,
          registrant_country: entry.registrant_country,
          registrant_phone: entry.registrant_phone,
          registrant_phone_ext: entry.registrant_phone_ext,
          registrant_fax: entry.registrant_fax,
          registrant_fax_ext: entry.registrant_fax_ext,
          registrant_email: entry.registrant_email,
          registry_admin_id: entry.registry_admin_id
        },
        DNS: {
          primary_name_server: entry.primary_name_server,
          primary_mx_server: entry.primary_mx_server,
          primary_a_record: entry.primary_a_record,
          primary_aaaa_record: entry.primary_aaaa_record
        },
        Traffic: {
          organic_search_traffic: entry.organic_search_traffic,
          paid_search_traffic: entry.paid_search_traffic,
          backlinks: entry.backlinks,
          top_organic_country_visitor: entry.top_organic_country_visitor,
          top_organic_country_visitor_percent: entry.top_organic_country_visitor_percent,
          local_organic_visitor: entry.local_organic_visitor,
          local_organic_visitor_percent: entry.local_organic_visitor_percent,
          top_paid_country_visitor: entry.top_paid_country_visitor,
          top_paid_country_visitor_percent: entry.top_paid_country_visitor_percent,
          local_paid_visitor: entry.local_paid_visitor,
          local_paid_visitor_percent: entry.local_paid_visitor_percent,
          top_organic_keywords: entry.top_organic_keywords,
          top_paid_keywords: entry.top_paid_keywords,
          keywords_by_intent: entry.keywords_by_intent,
          main_organic_competitors: entry.main_organic_competitors,
          main_organic_competitors_count: entry.main_organic_competitors_count,
          top_anchors: entry.top_anchors,
          top_outbound_domain: entry.top_outbound_domain,
          unique_visitors: entry.unique_visitors,
          pages_per_visit: entry.pages_per_visit,
          avg_visit_duration: entry.avg_visit_duration,
          bounce_rate: entry.bounce_rate,
          market_share: entry.market_share,
          market_traffic: entry.market_traffic,
          direct_traffic_sources: entry.direct_traffic_sources,
          referral_traffic_sources: entry.referral_traffic_sources,
          organic_search_traffic_sources: entry.organic_search_traffic_sources,
          paid_search_traffic_sources: entry.paid_search_traffic_sources,
          organic_social_traffic_sources: entry.organic_social_traffic_sources,
          paid_social_traffic_sources: entry.paid_social_traffic_sources,
          email_traffic_sources: entry.email_traffic_sources,
          display_ads_traffic_sources: entry.display_ads_traffic_sources,
          website_ranking: entry.website_ranking,
          website_country_ranking: entry.website_country_ranking,
          website_operating_category: entry.website_operating_category,
          website_ranking_category: entry.website_ranking_category,
          website_country_ranking_category: entry.website_country_ranking_category
        },
        Infrastructure: {
          miscellaneous_unclassified: entry.miscellaneous_unclassified,
          widgets: entry.widgets,
          analytics: entry.analytics,
          comment_systems: entry.comment_systems,
          security: entry.security,
          font_scripts: entry.font_scripts,
          cdn: entry.cdn,
          marketing_automation: entry.marketing_automation,
          advertising: entry.advertising,
          webcams: entry.webcams,
          tag_managers: entry.tag_managers,
          live_chat: entry.live_chat,
          javascript_libraries: entry.javascript_libraries,
          cookie_compliance: entry.cookie_compliance,
          accessibility: entry.accessibility,
          ssl_tls_certificate_authorities: entry.ssl_tls_certificate_authorities,
          affiliate_programs: entry.affiliate_programs,
          appointment_scheduling: entry.appointment_scheduling,
          surveys: entry.surveys,
          ab_testing: entry.ab_testing,
          email: entry.email,
          personalisation: entry.personalisation,
          retargeting: entry.retarging,
          rum: entry.rum,
          geolocation: entry.geolocation,
          browser_fingerprinting: entry.browser_fingerprinting,
          loyalty_rewards: entry.loyalty_rewards,
          feature_management: entry.feature_management,
          segmentation: entry.segmentation,
          hosting: entry.hosting,
          translation: entry.translation,
          reviews: entry.reviews,
          buy_now_pay_later: entry.buy_now_pay_later,
          performance: entry.performance,
          reservations_delivery: entry.reservations_delivery,
          referral_marketing: entry.referral_marketing,
          digital_asset_management: entry.digital_asset_management,
          content_curation: entry.content_curation,
          customer_data_platform: entry.customer_data_platform,
          cart_abandonment: entry.cart_abandonment,
          shipping_carriers: entry.shipping_carriers,
          recruitment_staffing: entry.recruitment_staffing,
          returns: entry.returns,
          livestreaming: entry.livestreaming,
          ticket_booking: entry.ticket_booking,
          augmented_reality: entry.augmented_reality,
          domain_parking: entry.domain_parking,
          fundraising_donations: entry.fundraising_donations,
          javascript_frameworks: entry.javascript_frameworks,
          web_servers: entry.web_servers,
          mobile_frameworks: entry.mobile_frameworks,
          payment_processors: entry.payment_processors,
          seo: entry.seo,
          user_onboarding: entry.user_onboarding,
          containers: entry.containers,
          paas: entry.paas,
          iaas: entry.iaas,
          wordpress_plugins: entry.wordpress_plugins,
          shopify_apps: entry.shopify_apps,
          form_builders: entry.form_builders,
          video_players: entry.video_players,
          web_frameworks: entry.web_frameworks,
          caching: entry.caching,
          web_server_extensions: entry.web_server_extensions,
          reverse_proxies: entry.reverse_proxies,
          load_balancers: entry.load_balancers,
          ui_frameworks: entry.ui_frameworks,
          wordpress_themes: entry.wordpress_themes,
          shopify_themes: entry.shopify_themes,
          drupal_themes: entry.drupal_themes,
          javascript_graphics: entry.javascript_graphics,
          operating_systems: entry.operating_systems,
          maps: entry.maps,
          authentication: entry.authentication,
          cross_border_ecommerce: entry.cross_border_ecommerce,
          fulfilment: entry.fulfilment,
          ecommerce_frontends: entry.ecommerce_frontends,
          rich_text_editors: entry.rich_text_editors,
          programming_languages: entry.programming_languages,
          databases_service: entry.databases_service,
          crm: entry.crm,
          cryptominers: entry.cryptominers,
          editor: entry.editor,
          search_engines: entry.search_engines,
          ci: entry.ci,
          database_managers: entry.database_managers,
          documentation_tools: entry.documentation_tools,
          hosting_panels: entry.hosting_panels,
          issue_trackers: entry.issue_trackers,
          webmail: entry.webmail,
          network_services: entry.network_services,
          development: entry.development,
          network_storage: entry.network_storage,
          cms: entry.cms,
          message_boards: entry.message_boards,
          ecommerce: entry.ecommerce,
          photo_galleries: entry.photo_galleries,
          wikis: entry.wikis,
          blogs: entry.blogs,
          lms: entry.lms,
          media_servers: entry.media_servers,
          remote_access: entry.remote_access,
          feed_readers: entry.feed_readers,
          dms: entry.dms,
          page_builder: entry.page_builder,
          accounting: entry.accounting,
          static_site_generators: entry.static_site_generators
        },
        Social: {
          phone_number: entry.phone_number,
          skype: entry.skype,
          whatsapp: entry.whatsapp,
          email_address: entry.email_address,
          email_address_verified: entry.email_address_verified,
          email_address_safe: entry.email_address_safe,
          twitter: entry.twitter,
          facebook: entry.facebook,
          instagram: entry.instagram,
          github: entry.github,
          tiktok: entry.tiktok,
          youtube: entry.youtube,
          pinterest: entry.pinterest,
          linkedin: entry.linkedin,
          owler: entry.owler,
          title: entry.title,
          description: entry.description,
          copyright: entry.copyright,
          copyright_year: entry.copyright_year,
          company_name: entry.company_name,
          inferred_company_name: entry.inferred_company_name,
          industry: entry.industry,
          about: entry.about,
          locations: entry.locations,
          company_size: entry.company_size,
          company_type: entry.company_type,
          company_founded: entry.company_founded,
          people: entry.people,
          medianet: entry.medianet,
          facebook_services: entry.facebook_services
        },
        Security: {
          cert_organisation: entry.cert_organisation,
          cert_country: entry.cert_country,
          cert_state: entry.cert_state,
          cert_locality: entry.cert_locality,
          cert_issuer: entry.cert_issuer,
          cert_protocol: entry.cert_protocol,
          cert_expiry: entry.cert_expiry,
          spf_record: entry.spf_record,
          dmarc_record: entry.dmarc_record,
          ssl_tls_enabled: entry.ssl_tls_enabled
        }
      };
    });
  }
}